/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:558967:
  appc.background(230);
} //_CODE_:window1:558967:

public void BPMSlider(GCustomSlider source, GEvent event) { //_CODE_:BPM:399879:
  int newTempo = int(source.getValueF());
  if (demoEqualizer.piece != null) {
    demoEqualizer.piece.tempo = newTempo;
  }
} //_CODE_:BPM:399879:

public void UndoClicked(GButton source, GEvent event) { //_CODE_:UndoButton:726321:
  editManager.undo();
} //_CODE_:UndoButton:726321:

public void RedoClicked(GButton source, GEvent event) { //_CODE_:RedoButton:317422:
  editManager.redo();
} //_CODE_:RedoButton:317422:

public void dropList1_click1(GDropList source, GEvent event) { //_CODE_:NoteKey:363558:
  int selected = source.getSelectedIndex();
  float[] durations = {4.0, 2.0, 1.0, 0.5, 0.25};
  // Store this somewhere accessible when placing notes
  println("Selected duration: " + durations[selected]);
} //_CODE_:NoteKey:363558:

public void PlayClicked(GButton source, GEvent event) { //_CODE_:PlayButton:426691:
  if (demoEqualizer.piece == null) return;
  
  if (demoEqualizer.piece.playing) {
    demoEqualizer.piece.stopPlayback();
    source.setText("Play");
  } else {
    demoEqualizer.piece.startPlayback();
    source.setText("Pause");
  }
} //_CODE_:PlayButton:426691:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 500, 400, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  BPM = new GCustomSlider(window1, 26, 96, 100, 40, "grey_blue");
  BPM.setLimits(0.5, 0.0, 1.0);
  BPM.setNumberFormat(G4P.DECIMAL, 2);
  BPM.setOpaque(false);
  BPM.addEventHandler(this, "BPMSlider");
  UndoButton = new GButton(window1, 37, 31, 80, 30);
  UndoButton.setText("Undo");
  UndoButton.addEventHandler(this, "UndoClicked");
  RedoButton = new GButton(window1, 131, 32, 81, 30);
  RedoButton.setText("Redo");
  RedoButton.addEventHandler(this, "RedoClicked");
  NoteKey = new GDropList(window1, 207, 98, 90, 80, 3, 10);
  NoteKey.setItems(loadStrings("noteDurations.txt"), 0);
  NoteKey.addEventHandler(this, "dropList1_click1");
  Notes = new GLabel(window1, 210, 66, 80, 20);
  Notes.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  Notes.setText("Note");
  Notes.setOpaque(false);
  PlayButton = new GButton(window1, 293, 30, 106, 30);
  PlayButton.setText("Play/Pause");
  PlayButton.addEventHandler(this, "PlayClicked");
  label1 = new GLabel(window1, 36, 72, 80, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("BPM");
  label1.setOpaque(false);
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GCustomSlider BPM; 
GButton UndoButton; 
GButton RedoButton; 
GDropList NoteKey; 
GLabel Notes; 
GButton PlayButton; 
GLabel label1; 
